//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1_NGSG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Multyproperty
    {
        public string Comunne { get; set; }
        public string Block { get; set; }
        public string Site { get; set; }
        public string Rut { get; set; }
        public double Percentage { get; set; }
        public string Page { get; set; }
        public string InscriptionNumber { get; set; }
        public int InscriptionYear { get; set; }
        public System.DateTime InscriptionDate { get; set; }
        public int StartCurrencyYear { get; set; }
        public Nullable<int> EndCurrencyYear { get; set; }
    }
}
