//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inscription()
        {
            this.Acquirers = new HashSet<Acquirer>();
            this.Alienators = new HashSet<Alienator>();
        }
    
        public int AtentionNumber { get; set; }
        public string CNE { get; set; }
        public string Comunne { get; set; }
        public string Block { get; set; }
        public string Site { get; set; }
        public string Page { get; set; }
        public string InscriptionNumber { get; set; }
        public System.DateTime InscriptionDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acquirer> Acquirers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alienator> Alienators { get; set; }
    }
}
