//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BienesRaicesDBEntities : DbContext
    {
        public BienesRaicesDBEntities()
            : base("name=BienesRaicesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acquirer> Acquirers { get; set; }
        public virtual DbSet<Alienator> Alienators { get; set; }
        public virtual DbSet<Inscription> Inscriptions { get; set; }
        public virtual DbSet<Multyproperty> Multyproperties { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
    }
}
